service: starter-dev-backend
frameworkVersion: '3'
useDotenv: true

plugins:
  - serverless-domain-manager
  - serverless-bundle
  - serverless-offline

custom:
  customDomain: # serverless-domain-manager
    domainName: api.starter.dev
    stage: production
    endpointType: 'regional'
    apiType: http
    certificateName: '*.starter.dev'

  serverless-offline: # serverless-offline
    httpPort: 4000

provider:
  name: aws
  profile: starterdev
  runtime: nodejs14.x
  environment:
    COOKIE_SECRET: ${env:COOKIE_SECRET}
    GITHUB_CLIENT_ID: ${env:X_GITHUB_CLIENT_ID}
    GITHUB_CLIENT_SECRET: ${env:X_GITHUB_CLIENT_SECRET}
    GITHUB_OAUTH_URL: ${env:X_GITHUB_OAUTH_URL}
    SERVER_BASE_URL: ${env:SERVER_BASE_URL}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'
